Display avatar placeholder for new user.
lonnieezell/Bonfire2 pull request #11
Opened 2021-09-29 19:30 UTC by kgrruz

Allow display avatar placeholder using random string(on user creation or similar situations).

2021-09-29 20:24 UTC, lonnieezell requested changes
Good catch! And thanks for the PR.  I think we can clean it up a touch, though.

2021-09-29 20:24 UTC, lonnieezell commented on app/Entities/User.php
> +        // Generate random string for avatar placeholder
Good catch - but I wouldn't force a random parameter here. Instead, if $idString is empty after checking for names, username, email, then give it a random string then. That way it's automatic. And a bit cleaner.

2021-09-29 20:24 UTC, lonnieezell commented on bonfire/Modules/Users/Views/form.php
> +                                <?= isset($user) ? $user->renderAvatar(140) : (new \App\Entities\User())->renderAvatar(140,true) ?>
Changing it like discussed above negates the need for the boolean here.

2021-10-01 14:15 UTC, lonnieezell approved these changes

2021-10-01 14:15 UTC, merged

2021-10-02 11:50 UTC, MGatner commented on app/Entities/User.php
> +    {
This makes me think the style Fixer was not run.