Add custom 2FA based on default codeigniter4/shield email 2FA
lonnieezell/Bonfire2 pull request #416
Opened 2024-02-16 15:46 UTC by kgrruz

Add custom 2FA based on default codeigniter4/shield email 2FA. Just to make use of the themes.

2024-02-16 15:55 UTC, lonnieezell requested changes
Thanks for this! Definitely a missed piece. 

I see you're extending the action from Shieid - that's perfect. Because of that please delete an methods in this class that don' specifically need to be here for theming purposes. 

Actually, IIRC the Actions use a Themeable trait that only provides `$this->view()` method. Would it be possible to ONLY override that method in this action to make use of the theme? Then all of the other methods wouldn't have to be duplicated which would make it safer then us having to constantly update those files when the logic changes?

2024-02-16 16:39 UTC, kgrruz commented
Done. Thank you for the explanation. If any other changes are needed, just tell me.

2025-01-14 11:01 UTC, dgvirtual commented
From what I see @kgrruz , is the getIdentity method a copy of the original shield method? Perhaps it should also be removed?

2025-01-14 16:48 UTC, dgvirtual commented
Starting off with your extended class, I have added a complete implementation at #501

2025-01-18 09:17 UTC, dgvirtual commented
Adapting your code in #501 I made a complete solution. So I am closing this PR. Thanks for contribution.

2025-01-18 09:17 UTC, closed without merging