WIP: feat(component-renderer): look for components in app path
lonnieezell/Bonfire2 pull request #9
Opened 2021-09-01 10:43 UTC by yassinedoghri

Hey @lonnieezell, I've made a not so interesting change in order to create the PR for discussion.

After the comment I've made (https://github.com/lonnieezell/Bonfire2/issues/5#issuecomment-908423807), I now realize that the structure of Bonfire2 is quite different from what I have, so I'd like to know what you are thinking about when locating view components.

If I understand correctly, in Bonfire2, each view in a theme can access the local components in the theme folder. And it would be nice to have a way to access common base components like buttons, links, form elements, or whatever to use across themes? So, one way would be to consider the default views folder a good place to put them, or even a Components folder directly in the default app path or themes path? Or another way would be to add a Components config file where we would add other discovery paths?

Also, I'm thinking maybe we would want to share common components to multiple themes but not all. For instance, Admin and Auth themes would have the same base components that the App would not need/share. So maybe the configuration should be done in the Theme class?

One more thing, when locating components, the Theme class is called to get the path, creating a coupling that may not be ideal for the future view components library.

I don't use themes for my project yet, I have a ViewComponents config file where I put the paths to look in. Then, I compare them with the current view path when locating the Components.

Anyways, sorry for the long comment, still trying to figure things out 😅

2021-11-19 03:42 UTC, lonnieezell commented
Wow - so sorry I let this one slip by. 

If you're still around and interested I think making a config setting to specify the backup folders to look in would be the way to go. By default just having app/Views would be great.

2021-11-23 09:54 UTC, yassinedoghri commented
Hey, no worries, I've worked on it on my project. I'll work on implementing it here sometime this week 🙂

2021-11-23 16:10 UTC, lonnieezell commented
Awesome. Looking forward to it!

2021-11-28 15:58 UTC, yassinedoghri commented
As promised, I've pushed the changes :slightly_smiling_face: 

Now, as a fallback, the ComponentRenderer's `locateView()` method will check for the component in the paths defined in the Bonfire config (the `$componentsLookupPaths` property to be exact).

Let me know if there are any changes to be made!

2021-11-29 04:08 UTC, lonnieezell requested changes
A simple enough change. Looks good except for relocating the config setting, please.

2021-11-29 04:08 UTC, lonnieezell commented on app/Config/Bonfire.php
> +    public $componentsLookupPaths = [
This is great, but please add to `app/Config/Themes.php` as it has a components-related setting there already.

2021-12-01 09:28 UTC, yassinedoghri commented
I've  made the change you requested, sorry I didn't see the Themes config!

2021-12-07 15:09 UTC, lonnieezell approved these changes
Looks great. Thanks for this!  Now one of these days I have to get back and explore the regexes some more to make it able to get values from the tag's attributes. :)

2021-12-07 15:10 UTC, merged

2021-12-08 08:50 UTC, yassinedoghri commented
> Looks great. Thanks for this! Now one of these days I have to get back and explore the regexes some more to make it able to get values from the tag's attributes. :)

@lonnieezell Well, for what it's worth, I've come up with a solution for this but it's kind of a hack, not sure if it's any good (mostly performance wise): I serialize the value in the view to then deserialize it in the component class.

Here's an example to pass an array of options for a multiselect component:

```php
// in the view
<Forms.Field
    as="MultiSelect"
    id="roles"
    name="roles[]"
    label="<?= lang('Person.episode_form.roles') ?>"
    hint="<?= lang('Person.episode_form.roles_hint') ?>"
    options="<?= htmlspecialchars(json_encode($taxonomyOptions)) ?>"
    selected="<?= htmlspecialchars(json_encode(old('roles', []))) ?>"
    required="true"
/>
```

```php
// in the MultiSelect class component
public function setOptions(string $value): void
{
    $this->options = json_decode(html_entity_decode($value), true);
}
```

I do the same for other attributes when I need to cast the value to something other than string, here's the `required` attribute:

```php
public function setRequired(string $value): void
{
    $this->required = $value === 'true';
}
```

Haven't had the time to really think about it and the code could use some refactoring to have this abstracted. Just like for the Entity, I thought of having a `$cast` property to set the passed values in the desired type.

Hope this helps!